<?php 
    $name = $_POST['name']; // name ..
    $whatsapp = $_POST['whatsapp']; // whatsapp ...
    $email = $_POST['email']; // email ...
    $password = $_POST['password']; // password ...
    $confirm_password = $_POST['confirm_password']; // password ...
    // connection between php and database ( mysqli is use to connect php project with database) ..
    include('cn.php'); // for connection ...
    echo "Working";
?>